FROM python:latest

WORKDIR /app/fastapi

RUN pip install --upgrade pip && \
    pip install fastapi && \
    pip install uvicorn && \
    pip install fastapi_csrf_protect==0.2.1 && \
    pip install motor==2.5.1 && \
    pip install PyJWT==2.3.0 && \
    pip install passlib==1.7.4 && \
    pip install python-decouple==3.3